name: cosmos
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - astropy=5.2.2
  - asttokens=2.4.1
  - backcall=0.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.53.0
  - freetype=2.12.1
  - h2=4.1.0
  - healpy=1.16.5
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib-resources=6.4.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33l
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran5=13.2.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - llvmlite=0.41.1
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mpi=1.0
  - mpi4py=3.1.6
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.58.1
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openmpi=5.0.3
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pooch=1.8.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pyerfa=2.0.0.3
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysm3=3.4.0
  - pysocks=1.7.1
  - pytest=8.2.2
  - pytest-runner=6.0.0
  - python=3.8.19
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - readline=8.2
  - requests=2.32.3
  - scipy=1.10.1
  - setuptools=70.1.1
  - six=1.16.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.22.0
  - zstd=1.5.6
  - pip:
      - camb==1.5.5
      - cython==3.0.10
      - ducc0==0.34.0
      - e==1.4.5
      - lenspyx==2.0.5
      - mpmath==1.3.0
      - sympy==1.12.1
      - tqdm==4.66.4
      - git+https://github.com/carronj/plancklens.git
