name: cosmos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - astropy=6.0.1
  - astropy-iers-data=0.2024.9.2.0.33.23
  - asttokens=2.4.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - camb=1.5.8
  - certifi=2024.8.30
  - cfitsio=4.4.1
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.53.1
  - freetype=2.12.1
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gfortran_impl_linux-64=12.4.0
  - gfortran_linux-64=12.4.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - healpy=1.17.3
  - importlib-metadata=8.4.0
  - importlib-resources=6.4.4
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.4
  - ipykernel=6.28.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsanitizer=12.4.0
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyerfa=2.0.1.4
  - pygments=2.18.0
  - pyparsing=3.1.4
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - scipy=1.13.1
  - setuptools=73.0.1
  - six=1.16.0
  - stack_data=0.6.2
  - sympy=1.13.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zstd=1.5.6
  - pip:
      - ducc0==0.34.0
      - lenspyx==2.0.5
      - llvmlite==0.43.0
      - numba==0.60.0
      - pysm3==3.4.0
      - toml==0.10.2
      - tqdm==4.66.5
      - git+https://github.com/carronj/plancklens.git
